hashtags = ['jharkhandwithmodi',
 'surgingsilk', 'merapmmeraabhimaan', 'kiamadeinap',
 'dousupportnaxals', 'mizoramwithmodi',
 'timesofrahul', 'threadsofexcellence',
 'msmetextilesconclave',
 'bjp4jind', 'म्हारा_वोट_भाजपा_को',
 'parakramparv', 'technicaltextiles',
 'himachalkacu', 'congaapbhaibhai',
 'sizeindia', 'savekeralafromcommunists',
 'copypastencp', 'bjp4betterandhra',
 'jaihindkisena', 'congressinsultsairforce',
 'armedforcesweek2018', 'bogibeelbridge',
 'newindia4narishakti', 'congressdefencescams',
 'hooghly_chalo', 'pminprayagraj',
 'goodgovernanceday', 'amethikididismritiirani',
 'namowithtraders', 'corruptcongressfearsdemo',
 'artisanspeak', 'indiabolemodidobara',
 'urban_नक्सली_केजरीवाल',
 'zamanatke1000din',
 'yuvakemannkibaat',
 'congressframedamitshah',
 'mainbhichowkidar',
 'iafbacksrafale',
 'भारत_माता_की_जय',
 'namothon',
 'लक्ष्य_हमारा_मोदी_दोबारा',
 'congressagainstnationalsecurity',
 'आदर्शघोटाला_संघर्ष_यात्रा',
 'pminraebareli',
 'bjpforsamridhkisan',
 'facebookboomed',
 'badalrahihaikashi',
 'lawlessodisha',
 'rafailgandhi',
 'rahulkidefencedeals',
 'rahulgandhijavabdo',
 'ragafailonrafale',
 'bjpvijaysankalpbikerally',
 'successofmakeinindia',
 'pmkisan',
 'congresseurofighterscandal',
 'modimeinhaidum',
 'takingforwardhinducause',
 'myfirstvoteformodi',
 'shahforgandhinagar',
 'bjpkamaljyoti',
 'maikamalkhilaneayahu',
 'उत्तरप्रदेश_विजय_संकल्प',
 'removetraitorsfromdu',
 'modiagain2019',
 'devendra4maharashtra',
 'andhrawithmodi',
 'jaihobc',
 'armedforcesflagday',
 'nris4modi',
 'modifiedtextiles',
 'meraparivarbhajapaparivar',
 'modifiedjobs',
 'gappupappu']
